name: testtt
favicon: null
layout_spectrum: 0.64127
typography_spectrum: 0.82032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#292b37'
    - '#a28f6e'
    - '#e6dbbd'
    - '#a2e8d5'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
